### ISSUE TITLE
Deploy to production

### ISSUE THREAD

**Issue by DQGriffin** [RingCentral-Pro-Services/Croissant.js#1]
Please deploy to a production environment

#### Environment variables
- PORT

The port variable is optional. Croissant will run on port 3000 if the variable isn't defined

**Comment by rcjonathanking** [comment]
Hello! This is our first project working together. We need a few pieces of information for the first deploy, such as if this is intended to be a dockerized app, what URL this app will need, and if you would like or need a staging environment. More than happy to setup a quick meeting or discuss over github.

**Comment by DQGriffin** [comment]
Hi there! 

- The app is intended to be dockerized
- For the URL, can we do croissant.ps.ringcentral.com?
- Yes, I'd like a staging environment

I'm happy to have a call if you need more information.

**Comment by rcjonathanking** [comment]
That's enough to get started. Would you like to control your dockerbuild file, or would you like us to handle that for you? Either is fine.

**Comment by rcjonathanking** [comment]
I need to do some modifications to your repo. Do you want me to push to development first, or work in main to pull from later?

**Comment by DQGriffin** [comment]
You can work in main.

**Comment by rcjonathanking** [comment]
Please verify your project in our staging environment. Once verified I will create the production version:

https://staging-croissant.ps.ringcentral.com/

**Comment by DQGriffin** [comment]
Verified. Thank you!

**Comment by rcjonathanking** [comment]
https://croissant.ps.ringcentral.com/

Closing out the issue. Whenever you need a new release, just push the current code to master. It will create a new docker image, tag me in a new issue, and I can put it into place on staging or prod. If you would like to be able to release to staging on your own, just let me know and we can run through that (quick and easy) process.
