### ISSUE TITLE
Deploy to production

### ISSUE THREAD

**Issue by DQGriffin** [RingCentral-Pro-Services/Croissant.js#2]
Please deploy the latest changes to production.

**Comment by rcjonathanking** [comment]
@DQGriffin I apologize, I have been on PTO. I see the latest build of this croissant is not in staging. Do you still want this to go straight to prod?

**Comment by DQGriffin** [comment]
No worries @rcjonathanking. We can deploy straight to production. Also, can I take you up on that offer to show me how to deploy to staging myself?

**Comment by rcjonathanking** [comment]
@DQGriffin sure, when are you free today? Do you want the latest in prod, and also pushed to staging?

**Comment by DQGriffin** [comment]
Yes, let's deploy to both production and staging. I'm free from 12PM Eastern to 2:30PM Eastern, then again from 3:30PM to 4PM.

**Comment by rcjonathanking** [comment]
Im in some meetings right now, lets do your 2:30PM, that's 12:30 MST for me and I am free during that time. We can deploy your current code then and I can have you "drive" so we can walk through the steps. It is all super simple.

**Comment by rcjonathanking** [comment]
Deployed to staging and prod.
